default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password:
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  database: multi_thread_b_development

test:
  <<: *default
  database: multi_thread_b_test

production:
  <<: *default
  database: multi_thread_b_production
  username: root
  password:
